### ISSUE TITLE
institutional skin lost when using login button or request button

### ISSUE THREAD

**Issue by ajones3066** [NYULibraries/getit#159]
When in an IP address space outside of the campus, the institutional skin is lost when clicking on the request button or when clicking on the 'login' button in the upper right corner.  this has led to confusion about whether students are in a new school service or in the wrong place.

**Comment by barnabyalter** [comment]
@ajones3066 I fixed this for GetIt in dev and will be pushing through to production this week. Know that this is only fixed for logging into GetIt. I added issues for doing the same from Primo and Eshelf. Thanks for bringing this to my attention.
