### ISSUE TITLE
Ebrary language

### ISSUE THREAD

**Issue by andrewbattista** [NYULibraries/getit#229]
There's language in Umlaut that references Ebrary ( I think on this page: https://github.com/NYULibraries/getit/blob/06a6c3a28e70500b025c7d1842ea92feeab107a4/app/views/resolve/_fulltext_response_item.html.erb). Needs to be changed to Ebook Central.

**Comment by barnabyalter** [comment]
@andrewbattista The display logic relies on the URL from SFX containing "site.ebrary.com/lib/nyulibrary", which was the base URL for all ebrary resources. Is there a new base URL we can key off of for Ebook Central? Also is this exactly as the text should appear: "Ebook Central"? Also, when will the change be ready in production? Already? Tx

cc @hab278 Please reference this chore: https://www.pivotaltracker.com/n/projects/1057800/stories/149886757

**Comment by barnabyalter** [comment]
@andrewbattista I also am assuming that you want this same change where the logic is duplicated in Primo: https://github.com/NYULibraries/primo-web-custom/blob/master/views/common/link.jsp#L20-L22

cc @hab278 https://github.com/NYULibraries/primo-web-custom/issues/251

**Comment by andrewbattista** [comment]
Sorry for the delay on this. Was traveling. It looks like it's been updated in GetIt. Thanks!

**Comment by ajones3066** [comment]
Andrew-

Is everything that was hosted in DASH in ebook central?  I thought things ebrary didn’t have in their previous platform were staying in the old platform?  You may want to verify with Bill M.

Allen

**Comment by barnabyalter** [comment]
@andrewbattista I haven't updated anything in GetIt. Can you show me an example of a page you're seeing with it updated? That might be coming directly from SFX.

**Comment by andrewbattista** [comment]
@barnabyalter hmm... Here's a link to a page that has it: https://getit.library.nyu.edu/go/9428560

**Comment by barnabyalter** [comment]
@andrewbattista Yeah so it looks like that's the raw data coming our of SFX. The existing functionality has these comments:

```
# Display 'NYU ebrary' if the URL is from NYU's ebrary.
# Masks the fact that the data does not come correct.
```

So maybe the ebrary data didn't all say "NYU ebrary" so we just used the source to normalize that (?). I'd suggest just removing that logic entirely.
