### ISSUE TITLE
Update services.yml to include NS_Primo

### ISSUE THREAD

**Issue by ajones3066** [NYULibraries/getit#286]
I would like to have an institution-specific NYU_PRIMO instance so that ONLY NS Sfx links show and that we can have different regular expression filtering for Primo linktorsrc links.

**Comment by barnabyalter** [comment]
@ajones3066 Please touch base with Rachel about adding this as part of the OVP project we'll start next year. We won't have many cycles between now and then.

In the meantime you can keep an eye on this branch: https://github.com/NYULibraries/getit/commits/feature/ns_primo
