### ISSUE TITLE
Add E-ZBorrow option to Umlaut

### ISSUE THREAD

**Issue by kristinarose** [NYULibraries/getit#33]
I wrote several user stories that cover these changes - please let me know if those are usable.

This update applies only to the following:
E-Zborrow eligible patron status + unavailable book (checked out or items with item processing status)

If those conditions exist, Umlaut should display the E-ZBorrow request link as the first option with ILL as the second option.

Language for addition of E-ZBorrow link:
Request this item from another library via E-ZBorrow (Link to E-ZBorrow)
Books delivered within 3-5 days with a borrowing period of 12 weeks.

ILL option would remain the same.

**Comment by barnabyalter** [comment]
Fixed by most massive commit: https://github.com/NYULibraries/getit/commit/4ba360646ba449ff1a6493f657a9ea42b9ec7bf4
