### ISSUE TITLE
Move InstitutionsHelper to nyulibraries-assets

### ISSUE THREAD

**Issue by hab278** [NYULibraries/getit#53]
Move [this](https://github.com/NYULibraries/getit/blob/feature/oauth2-integration/app/helpers/institutions_helper.rb) into [this](https://github.com/NYULibraries/nyulibraries-assets/blob/master/app/helpers/nyulibraries/assets/institution_helper.rb)

**Comment by barnabyalter** [comment]
Looks like this waas done
